AWSTemplateFormatVersion: 2010-09-09
Resources:
  DefineSafeApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: DefineSafeApi
      Description: An API for the define safe application
      FailOnWarnings: true
      EndpointConfiguration:
        Types: ["REGIONAL"]
  DefineSafeApiStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      DeploymentId:
        Ref: ApiDeployment
      MethodSettings:
        - DataTraceEnabled: true
          HttpMethod: '*'
          ResourcePath: /*
      RestApiId:
        Ref: DefineSafeApi
      StageName: LATEST
  ApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - PlanRequest
    Properties:
      RestApiId:
        Ref: DefineSafeApi
      StageName: DummyStage
# Authentication
  LambdaPermissionForAuth:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: 'arn:aws:lambda:us-east-1:042537148068:function:CustomAuthorizer'
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Join':
          - ''
          - - 'arn:aws:execute-api:'
            - Ref: 'AWS::Region'
            - ':'
            - Ref: 'AWS::AccountId'
            - ':'
            - Ref: DefineSafeApi
            - /*
  Authorizer:
    Type : 'AWS::ApiGateway::Authorizer'
    Properties:
      AuthorizerCredentials: 'arn:aws:iam::042537148068:role/AWSLambdaBasicExecutionRole-CustomAuthorizer'
      AuthorizerUri:
          'Fn::Join':
          - ''
          - - 'arn:aws:apigateway:'
            - Ref: 'AWS::Region'
            - ':lambda:path/2015-03-31/functions/'
            - 'arn:aws:lambda:us-east-1:042537148068:function:CustomAuthorizer'
            - /invocations
      Type: TOKEN
      IdentitySource: method.request.header.Auth
      Name: jwt-rsa-custom-authorizer
      RestApiId: 
        Ref: DefineSafeApi
# Resources
  PlanResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId:
        Ref: DefineSafeApi
      ParentId:
        'Fn::GetAtt':
          - DefineSafeApi
          - RootResourceId
      PathPart: plan
# GetPlanByUserId
  LambdaPermissions:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: 'arn:aws:lambda:us-east-1:042537148068:function:GetPlanByUserId'
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Join':
          - ''
          - - 'arn:aws:execute-api:'
            - Ref: 'AWS::Region'
            - ':'
            - Ref: 'AWS::AccountId'
            - ':'
            - Ref: DefineSafeApi
            - /*
  PlanOptions:
    DependsOn:
      - LambdaPermissions
      - PlanResource
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId:
        Ref: DefineSafeApi
      ResourceId:
        Ref: PlanResource
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  PlanRequest:
    DependsOn: 
      - LambdaPermissions
      - PlanResource
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      HttpMethod: GET
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          'Fn::Join':
            - ''
            - - 'arn:aws:apigateway:'
              - Ref: 'AWS::Region'
              - ':lambda:path/2015-03-31/functions/'
              - 'arn:aws:lambda:us-east-1:042537148068:function:GetPlanByUserId'
              - /invocations
        IntegrationResponses:
          - StatusCode: 200
        RequestTemplates:
          application/json:
            'Fn::Join':
              - ''
              - - '{'
                - '"name": "$input.params(''user_id'')"'
                - '}'
      RequestParameters:
        method.request.querystring.name: false
      ResourceId:
        Ref: PlanResource
      RestApiId:
        Ref: DefineSafeApi
      MethodResponses:
        - StatusCode: 200
# UpdatePlanById
  LambdaPermissions2:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: 'arn:aws:lambda:us-east-1:042537148068:function:UpdatePlanById'
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Join':
          - ''
          - - 'arn:aws:execute-api:'
            - Ref: 'AWS::Region'
            - ':'
            - Ref: 'AWS::AccountId'
            - ':'
            - Ref: DefineSafeApi
            - /*
  PlanRequest2:
    DependsOn: 
      - LambdaPermissions2
      - PlanResource
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: PUT
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          'Fn::Join':
            - ''
            - - 'arn:aws:apigateway:'
              - Ref: 'AWS::Region'
              - ':lambda:path/2015-03-31/functions/'
              - 'arn:aws:lambda:us-east-1:042537148068:function:UpdatePlanById'
              - /invocations
        IntegrationResponses:
          - StatusCode: 200
      ResourceId:
        Ref: PlanResource
      RestApiId:
        Ref: DefineSafeApi
      MethodResponses:
        - StatusCode: 200
# CreatePlan
  LambdaPermissions3:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: 'arn:aws:lambda:us-east-1:042537148068:function:CreatePlan'
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Join':
          - ''
          - - 'arn:aws:execute-api:'
            - Ref: 'AWS::Region'
            - ':'
            - Ref: 'AWS::AccountId'
            - ':'
            - Ref: DefineSafeApi
            - /*
  PlanRequest3:
    DependsOn: 
      - LambdaPermissions3
      - PlanResource
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          'Fn::Join':
            - ''
            - - 'arn:aws:apigateway:'
              - Ref: 'AWS::Region'
              - ':lambda:path/2015-03-31/functions/'
              - 'arn:aws:lambda:us-east-1:042537148068:function:CreatePlan'
              - /invocations
        IntegrationResponses:
          - StatusCode: 200
      ResourceId:
        Ref: PlanResource
      RestApiId:
        Ref: DefineSafeApi
      MethodResponses:
        - StatusCode: 200
