AWSTemplateFormatVersion: 2010-09-09
Resources:
  DefineSafeApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: DefineSafeApi
      Description: An API for the define safe application
      FailOnWarnings: true
      EndpointConfiguration:
        Types: ["REGIONAL"]
  DefineSafeApiStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      DeploymentId:
        Ref: ApiDeployment
      MethodSettings:
        - DataTraceEnabled: true
          HttpMethod: '*'
          ResourcePath: /*
      RestApiId:
        Ref: DefineSafeApi
      StageName: v1
  ApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - GetPlanMethod
      - UpdatePlanMethod
      - CreatePlanMethod
      - AddMedicationMethod
      - GetAllPlansMethod
      - GetMedicationsMethod
      - RemoveMedicationMethod
    Properties:
      RestApiId:
        Ref: DefineSafeApi
# Authentication
  LambdaPermissionForAuth:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: 'arn:aws:lambda:us-east-1:042537148068:function:CustomAuthorizer'
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Join':
          - ''
          - - 'arn:aws:execute-api:'
            - Ref: 'AWS::Region'
            - ':'
            - Ref: 'AWS::AccountId'
            - ':'
            - Ref: DefineSafeApi
            - /*
# Custom Authorizer used by the entire API
  Authorizer:
    Type : 'AWS::ApiGateway::Authorizer'
    Properties:
      AuthorizerCredentials: 'arn:aws:iam::042537148068:role/AWSLambdaBasicExecutionRole-CustomAuthorizer'
      AuthorizerUri:
          'Fn::Join':
          - ''
          - - 'arn:aws:apigateway:'
            - Ref: 'AWS::Region'
            - ':lambda:path/2015-03-31/functions/'
            - 'arn:aws:lambda:us-east-1:042537148068:function:CustomAuthorizer'
            - /invocations
      Type: TOKEN
      IdentitySource: method.request.header.Authorization
      Name: jwt-rsa-custom-authorizer
      RestApiId: 
        Ref: DefineSafeApi
# Api Resources section
  PlanResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId:
        Ref: DefineSafeApi
      ParentId:
        'Fn::GetAtt':
          - DefineSafeApi
          - RootResourceId
      PathPart: plan
  PlansResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId:
        Ref: DefineSafeApi
      ParentId:
        'Fn::GetAtt':
          - DefineSafeApi
          - RootResourceId
      PathPart: plans
  MedicationResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId:
        Ref: DefineSafeApi
      ParentId:
        'Fn::GetAtt':
          - DefineSafeApi
          - RootResourceId
      PathPart: medication
  MedicationsResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId:
        Ref: DefineSafeApi
      ParentId:
        'Fn::GetAtt':
          - DefineSafeApi
          - RootResourceId
      PathPart: medications
# Resource Options for CORS
  PlanOptions:
    DependsOn:
      - PlanResource
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId:
        Ref: DefineSafeApi
      ResourceId:
        Ref: PlanResource
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,OPTIONS'" #This list must include all calls being made to this resource
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  PlansOptions:
    DependsOn:
      - PlansResource
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId:
        Ref: DefineSafeApi
      ResourceId:
        Ref: PlansResource
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'" #This list must include all calls being made to this resource
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  MedicationOptions:
    DependsOn:
      - MedicationResource
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId:
        Ref: DefineSafeApi
      ResourceId:
        Ref: MedicationResource
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'" #This list must include all calls being made to this resource
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  MedicationsOptions:
    DependsOn:
      - MedicationsResource
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId:
        Ref: DefineSafeApi
      ResourceId:
        Ref: MedicationsResource
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,OPTIONS'" #This list must include all calls being made to this resource
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
# Methods below here include a lambda permission and a method definition
# GetPlanByUserId
  GetPlanPermissions:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: 'arn:aws:lambda:us-east-1:042537148068:function:GetPlanByUserId'
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Join':
          - ''
          - - 'arn:aws:execute-api:'
            - Ref: 'AWS::Region'
            - ':'
            - Ref: 'AWS::AccountId'
            - ':'
            - Ref: DefineSafeApi
            - /*
  GetPlanMethod:
    DependsOn: 
      - GetPlanPermissions
      - PlanResource
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      HttpMethod: GET
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          'Fn::Join':
            - ''
            - - 'arn:aws:apigateway:'
              - Ref: 'AWS::Region'
              - ':lambda:path/2015-03-31/functions/'
              - 'arn:aws:lambda:us-east-1:042537148068:function:GetPlanByUserId'
              - /invocations
      ResourceId:
        Ref: PlanResource
      RestApiId:
        Ref: DefineSafeApi
      MethodResponses:
        - StatusCode: 200
# UpdatePlanById
  UpdatePlanPermissions:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: 'arn:aws:lambda:us-east-1:042537148068:function:UpdatePlanById'
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Join':
          - ''
          - - 'arn:aws:execute-api:'
            - Ref: 'AWS::Region'
            - ':'
            - Ref: 'AWS::AccountId'
            - ':'
            - Ref: DefineSafeApi
            - /*
  UpdatePlanMethod:
    DependsOn: 
      - UpdatePlanPermissions
      - PlanResource
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      HttpMethod: PUT
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          'Fn::Join':
            - ''
            - - 'arn:aws:apigateway:'
              - Ref: 'AWS::Region'
              - ':lambda:path/2015-03-31/functions/'
              - 'arn:aws:lambda:us-east-1:042537148068:function:UpdatePlanById'
              - /invocations
        IntegrationResponses:
          - StatusCode: 200
      ResourceId:
        Ref: PlanResource
      RestApiId:
        Ref: DefineSafeApi
      MethodResponses:
        - StatusCode: 200
# CreatePlan
  CreatePlanPermissions:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: 'arn:aws:lambda:us-east-1:042537148068:function:CreatePlan'
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Join':
          - ''
          - - 'arn:aws:execute-api:'
            - Ref: 'AWS::Region'
            - ':'
            - Ref: 'AWS::AccountId'
            - ':'
            - Ref: DefineSafeApi
            - /*
  CreatePlanMethod:
    DependsOn: 
      - CreatePlanPermissions
      - PlanResource
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      HttpMethod: POST
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          'Fn::Join':
            - ''
            - - 'arn:aws:apigateway:'
              - Ref: 'AWS::Region'
              - ':lambda:path/2015-03-31/functions/'
              - 'arn:aws:lambda:us-east-1:042537148068:function:CreatePlan'
              - /invocations
        IntegrationResponses:
          - StatusCode: 200
      ResourceId:
        Ref: PlanResource
      RestApiId:
        Ref: DefineSafeApi
      MethodResponses:
        - StatusCode: 200
# AddMedication
  AddMedicationPermissions:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: 'arn:aws:lambda:us-east-1:042537148068:function:AddMedication'
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Join':
          - ''
          - - 'arn:aws:execute-api:'
            - Ref: 'AWS::Region'
            - ':'
            - Ref: 'AWS::AccountId'
            - ':'
            - Ref: DefineSafeApi
            - /*
  AddMedicationMethod:
    DependsOn: 
      - AddMedicationPermissions
      - MedicationResource
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      HttpMethod: POST
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          'Fn::Join':
            - ''
            - - 'arn:aws:apigateway:'
              - Ref: 'AWS::Region'
              - ':lambda:path/2015-03-31/functions/'
              - 'arn:aws:lambda:us-east-1:042537148068:function:AddMedication'
              - /invocations
        IntegrationResponses:
          - StatusCode: 200
      ResourceId:
        Ref: MedicationResource
      RestApiId:
        Ref: DefineSafeApi
      MethodResponses:
        - StatusCode: 200
# RemoveMedication
  RemoveMedicationPermissions:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: 'arn:aws:lambda:us-east-1:042537148068:function:RemoveMedication'
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Join':
          - ''
          - - 'arn:aws:execute-api:'
            - Ref: 'AWS::Region'
            - ':'
            - Ref: 'AWS::AccountId'
            - ':'
            - Ref: DefineSafeApi
            - /*
  RemoveMedicationMethod:
    DependsOn: 
      - RemoveMedicationPermissions
      - MedicationResource
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      HttpMethod: DELETE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          'Fn::Join':
            - ''
            - - 'arn:aws:apigateway:'
              - Ref: 'AWS::Region'
              - ':lambda:path/2015-03-31/functions/'
              - 'arn:aws:lambda:us-east-1:042537148068:function:RemoveMedication'
              - /invocations
        IntegrationResponses:
          - StatusCode: 200
      ResourceId:
        Ref: MedicationResource
      RestApiId:
        Ref: DefineSafeApi
      MethodResponses:
        - StatusCode: 200
# GetAllPlans
  GetAllPlansPermissions:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: 'arn:aws:lambda:us-east-1:042537148068:function:GetAllPlans'
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Join':
          - ''
          - - 'arn:aws:execute-api:'
            - Ref: 'AWS::Region'
            - ':'
            - Ref: 'AWS::AccountId'
            - ':'
            - Ref: DefineSafeApi
            - /*
  GetAllPlansMethod:
    DependsOn: 
      - GetAllPlansPermissions
      - PlansResource
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      HttpMethod: GET
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          'Fn::Join':
            - ''
            - - 'arn:aws:apigateway:'
              - Ref: 'AWS::Region'
              - ':lambda:path/2015-03-31/functions/'
              - 'arn:aws:lambda:us-east-1:042537148068:function:GetAllPlans'
              - /invocations
        IntegrationResponses:
          - StatusCode: 200
      ResourceId:
        Ref: PlansResource
      RestApiId:
        Ref: DefineSafeApi
      MethodResponses:
        - StatusCode: 200
# GetMedications
  GetMedicationsPermissions:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: 'arn:aws:lambda:us-east-1:042537148068:function:GetMedications'
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Join':
          - ''
          - - 'arn:aws:execute-api:'
            - Ref: 'AWS::Region'
            - ':'
            - Ref: 'AWS::AccountId'
            - ':'
            - Ref: DefineSafeApi
            - /*
  GetMedicationsMethod:
    DependsOn: 
      - GetMedicationsPermissions
      - MedicationsResource
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      HttpMethod: GET
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          'Fn::Join':
            - ''
            - - 'arn:aws:apigateway:'
              - Ref: 'AWS::Region'
              - ':lambda:path/2015-03-31/functions/'
              - 'arn:aws:lambda:us-east-1:042537148068:function:GetMedications'
              - /invocations
        IntegrationResponses:
          - StatusCode: 200
      ResourceId:
        Ref: MedicationsResource
      RestApiId:
        Ref: DefineSafeApi
      MethodResponses:
        - StatusCode: 200
