#!/bin/bash

function create_matrix_output {
    arr=("$@")
    matrixOutput="files=["
    for i in "${arr[@]}"
    do
        matrixOutput+="\"$i\","
    done
    matrixOutput="${matrixOutput%,}]"
    echo $matrixOutput>&2
}