#!/bin/bash

function create_matrix_output {
    arr=("$@")
    matrixOutput="files={\"include\":["
    for i in "${arr[@]}"
    do
        matrixOutput+="\"$i\","
    done
    matrixOutput="${matrixOutput%,}]}"
    echo $matrixOutput>&2
}