#!/bin/bash

function has_changes {
    functionName=$(aws lambda list-functions --query "Functions[?FunctionName == '$1'].FunctionName" --output text --region "us-east-1")
    if [[ -z "$functionName" ]] # if the lambda does not exist
    then # return true (which looks like "return")
        return
    else # else check to see if the index file has changed - TODO: make this also check package.json or any .js files?
        fileContents=$(curl -s "https://raw.githubusercontent.com/charlenecoffman/definesafe-cf/main/src/Lambdas/$1/index.js")
        contentsLocation=$(aws lambda get-function --function-name $1 --query 'Code.Location')
        contentsLocation="${contentsLocation%\"}"
        contentsLocation="${contentsLocation#\"}"
        dirName="../deleteLater/$1"
        mkdir -p ../deleteLater
        mkdir $dirName
        curl -s $contentsLocation --output ${dirName}/$1_currentLambda.zip
        unzip -qq -d ${dirName} -o ${dirName}/$1_currentLambda.zip
        contentsOfLambda=$(<${dirName}/index.js)
        if [ "$fileContents" != "$contentsOfLambda" ]
        then
            return
        else
            false
        fi
    fi
}

function zip_any_with_changes {
    cd "$1"
    for i in */
    do
    if $(has_changes "${i%/}")
    then # zip it up and put in the matrix output
        (cd "$i"; zip -r "../${i%/}.zip" . -qq)
        echo "file=${i%/}" >> $GITHUB_OUTPUT
    fi
    done
}