#!/bin/bash

function=$(aws lambda list-functions --query "Functions[?FunctionName == '$1'].FunctionName" --output text --region "us-east-1")
if [[ -z "$function" ]]
then
    exit 1
else
    fileContents=$(curl -s "https://raw.githubusercontent.com/charlenecoffman/definesafe-cf/main/src/Lambdas/${i%/}/index.js")
    contentsLocation=$(aws lambda get-function --function-name ${i%/} --query 'Code.Location')
    contentsLocation="${contentsLocation%\"}"
    contentsLocation="${contentsLocation#\"}"
    dirName="../deleteLater/${i%/}"
    mkdir -p ../deleteLater
    mkdir $dirName
    curl -s $contentsLocation --output ${dirName}/${i%/}_currentLambda.zip
    unzip -qq -d ${dirName} -o ${dirName}/${i%/}_currentLambda.zip
    contentsOfLambda=$(<${dirName}/index.js)
    if [ "$fileContents" != "$contentsOfLambda" ]
    then
        exit 1
    else
        exit 0
    fi
fi
echo $1