name: CFDeployments
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS-ACCESS-KEY-ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS-SECRET-ACCESS-KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS-REGION: us-east-1
      - name: Check Stack Existance
        run: |
          status=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE UPDATE_COMPLETE --query "StackSummaries[?StackName=='DefineSafe-CF'] | [0].StackStatus")
          echo "::set-env name=STATUS::$status"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Create Stack If Doesn't Exist
        if: env.STATUS == ''
        run: |
          aws cloudformation create-stack --stack-name "DefineSafe-CF" --template-body file://src/ApiGateway/DefineSafeApi.yml --tags Key=Solution,Value=DefineSafe
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Add Template to S3
        if: env.STATUS != ''
        run: |
          timestamp=$(date '+%Y.%m.%d-%H.%M.%S')
          filename="DefineSafeApi-$timestamp.yml"
          aws s3 cp src/ApiGateway/DefineSafeApi.yml s3://cf-templates-1syem7yzq6ws3-us-east-1/${filename}
          echo "::set-env name=FILENAME::${filename}"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
      - name: Update Stack If Exists
        if: env.STATUS != ''
        run: |
          aws cloudformation deploy --stack-name "DefineSafe-CF" --template-file "s3://cf-templates-1syem7yzq6ws3-us-east-1/${env.FILENAME}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1