name: dev-CFDeployments
on:
  push:
    branches-ignore:
      - main

jobs:
  deploy-api-cf-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS-ACCESS-KEY-ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS-SECRET-ACCESS-KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS-REGION: us-east-1
      - name: Deploy Stack
        run: |
          aws cloudformation deploy --stack-name "dev-BeTheChange-CF" --template-file src/CloudFormationTemplates/dev-BeTheChangeApi.yml --no-fail-on-empty-changeset --tags Solution=BeTheChange
          apiId=$(aws apigateway get-rest-apis --query "items[?name == 'dev-BeTheChangeApi'].id | [0]" --output text --region "us-east-1")
          aws apigateway create-deployment --rest-api-id $apiId --stage-name v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
  deploy-tables-cf-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS-ACCESS-KEY-ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS-SECRET-ACCESS-KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS-REGION: us-east-1
      - name: Deploy Stack
        run: |
          aws cloudformation deploy --stack-name "dev-BeTheChangeTables-CF" --template-file src/CloudFormationTemplates/dev-BeTheChangeTables.yml --no-fail-on-empty-changeset --tags Solution=BeTheChange
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1