name: LambdaDeployments
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Zip up each function
        id: zipfunctions
        run: cd src/Lambdas && for i in */; do (cd "$i"; zip -r "../${i%/}.zip" .); done
      - name: Upload Zips to artifact container
        uses: actions/upload-artifact@master
        with:
          name: zips
          path: src/Lambdas/*.zip
  createMatrix:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      matrix: ${{steps.jsonMatrixOutput.outputs.matrix}}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Json Matrix Output
        id: jsonMatrixOutput
        run: |
          matrixOutput="{\"include\":["
          cd artifacts/zips && for i in ./*; do 
            f=$(echo "${i##*/}");
            filename=$(echo $f| cut  -d'.' -f 1);
            matrixOutput+="{\"file\":\"${filename}\"},"; 
          done
          matrixOutput+="]}"
          echo "::set-output name=matrix::${matrixOutput}"
  deploy:
    runs-on: ubuntu-latest
    needs: createMatrix
    strategy:
      matrix: ${{fromJson(needs.createMatrix.outputs.matrix)}}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS-ACCESS-KEY-ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS-SECRET-ACCESS-KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS-REGION: us-east-1
      - name: Check Function Existance
        run: |
          role=$(aws lambda list-functions --query 'Functions[?FunctionName == `${{matrix.file}}`].Role' --output text --region "us-east-1")
          echo "::set-env name=ROLE::$role"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Create Role & Function If Doesn't Exist
        if: env.ROLE == ''
        run: |
          echo "{\"Version\": \"2012-10-17\",\"Statement\": [{\"Effect\": \"Allow\", \"Action\": \"sts:AssumeRole\", \"Principal\": {\"Service\": \"lambda.amazonaws.com\"}}]}" > policyJson.json
          role=$(aws iam create-role --role-name "AWSLambdaBasicExecutionRole-${{ matrix.file }}" --assume-role-policy-document file://policyJson.json --region "us-east-1");
          echo $role > returnObject.json
          sleep 10s
          aws lambda create-function --function-name ${{matrix.file}} --runtime "nodejs12.x" --role "$(jq -r '.Role.Arn' returnObject.json)" --handler "index.handler" --zip-file fileb://zips/${{matrix.file}}.zip --region "us-east-1" --tags Solution=DefineSafe
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Checkout Code
        if: env.ROLE != ''
        uses: actions/checkout@v2
      - name: Get Last Modified Dates
        run: |
          fileLastModifiedDate=$(date -r src/Lambdas/${{matrix.file}}/index.js)
          lambdaLastModifiedDate=$(aws lambda get-function --function-name ${{matrix.file}} --query 'Configuration.LastModified')
          echo $fileLastModifiedDate          
          lambdaLastModifiedDate="${lambdaLastModifiedDate//\"/}"
          #lambdaLastModifiedDate="${lambdaLastModifiedDate//-//}"
          #lambdaLastModifiedDate="${lambdaLastModifiedDate/.000+0000/}"
          lambdaLastModifiedDate=$(date -d "$lambdaLastModifiedDate")
          echo $lambdaLastModifiedDate
          echo $(git log -1 --pretty:"format:%ci" https://github.com/charlenecoffman/definesafe-cf/src/Lambdas/${{matrix.file}}/index.js)
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Update Function If Exists
        if: env.UPDATE == 'true'
        run: aws lambda update-function-code --function-name ${{matrix.file}} --zip-file fileb://zips/${{matrix.file}}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
      - name: If function doesn't need updating, then do nothing
        if: env.UPDATE == 'false'
        run: echo "Nothing needed"